on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - 'deploy/**'
  
name: CI
jobs:
  solution:
    name: Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Solution
      run: dotnet build src/Promitor.DataGeneration.sln --configuration Release
  bicep:
    name: Bicep
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep file
    - name: Build Bicep Declaration
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: ./deploy/infrastructure.bicep