name: Deploy to Azure
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'deploy/**'
    - '.github/workflows/deploy-to-azure.yml'

jobs:
  deploy_to_prd:
      name: Deploy to PROD
      env:
        AZURE_RESOURCEGROUP_NAME: "promitor-automation-data-generation"
      environment:
        name: Promitor Data Generation (PRD)
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main
        name: Checkout code

          # Login to Azure
      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: Deploy to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/infrastructure.bicep
          deploymentName: infrastructure-run-${{ github.run_number }}
          failOnStdErr: true