name: Package Azure Function

on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows/package-azure-function.yml'
    - 'src/**'

env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  ARTIFACT_NAME: function-app-package
  DOTNET_VERSION: '3.1.x'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup .NET v${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create Azure Function Artifact
      run: dotnet publish ./src/AzureFunctions --configuration Release --output ${{ env.OUTPUT_PATH }}

    - name: Publish Azure Function Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_PATH }}